site_name: ctf-toolkit
site_url: https://xaxa-0x3f.github.io/ctf-toolkit/
repo_url: https://github.com/xaxa-0x3F/ctf-toolkit
repo_name: xaxa-0x3F/ctf-toolkit
site_author: xaxa-0x3f

theme:
  name: material
  palette:
    # Dark Mode (Default)
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    # Light Mode
    - scheme: default
      primary: red
      accent: deep-orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
    - toc.follow
  icon:
    repo: fontawesome/brands/github
    logo: material/security

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Toolkit:
    - Recon & Enumeration: recon.md
    - Web Exploitation: web.md
    - Crypto & Stego: crypto.md
    - Forensics & Logs: forensics.md
    - RevEng & Malware: reveng.md
    - PrivEsc & Shells: privesc.md
    - Password Cracking: passwords.md
  - Resources: resources.md